<?=link_tag('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback')."\n";?>
<?=link_tag('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css')."\n";?>
<?=link_tag(base_url('assets/plugins/overlayScrollbars/css/OverlayScrollbars.min.css'))."\n";?>
<?=link_tag(base_url('assets/dist/css/adminlte.min.css'))."\n";?>
<?=link_tag(base_url('assets/plugins/toastr/toastr.min.css'))."\n";?>
<?=link_tag(base_url('assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css'))."\n";?>
<?=link_tag(base_url('assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css'))."\n";?>
<?=link_tag(base_url('assets/plugins/datatables-buttons/css/buttons.bootstrap4.min.css'))."\n";?>
<?=script_tag("https://code.jquery.com/jquery-3.6.0.min.js")."\n";?>
<?=link_tag('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css')."\n";?>
<?=link_tag('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-timepicker/0.5.2/css/bootstrap-timepicker.min.css')."\n";?>
<?=script_tag(base_url('assets/common.js'))."\n";?>
<?=link_tag(base_url('assets/plugins/select2/css/select2.min.css'))."\n";?>
<?=link_tag(base_url('assets/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css'))."\n";?>
<?=link_tag(base_url('assets/custom.css'))."\n";?>
